### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by IancuOnescu** [IancuOnescu/poker-stats#3]
**Intermediate tasks:**
- [x] bankrolls
- [x] piechart with top winning hands per player/general
- [ ] showdown and non showdown winnings by month
- [x] benford
- [x] normal distribution comparison for outcome
- [ ] if we research enough and find a formula then do stuff with EV (expected value)
- [ ] probability to come to ruin

**Final tasks:**
- [ ] add explanations for each segment
- [ ] make plots look nice
